#!/bin/bash
# install.sh - Install ai-bu-status-report commands into Claude Code

set -e

COMMANDS_DIR="$HOME/.claude/commands"
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
SOURCE_DIR="$SCRIPT_DIR/commands"

echo "Installing ai-bu-status-report commands..."
echo ""

# Create the commands directory if it does not exist
mkdir -p "$COMMANDS_DIR"

# Copy command files
cp "$SOURCE_DIR/status-report.md" "$COMMANDS_DIR/status-report.md"
cp "$SOURCE_DIR/quarterly-review.md" "$COMMANDS_DIR/quarterly-review.md"
cp "$SOURCE_DIR/team-report.md" "$COMMANDS_DIR/team-report.md"
cp "$SOURCE_DIR/okr-update.md" "$COMMANDS_DIR/okr-update.md"
cp "$SOURCE_DIR/executive-summary.md" "$COMMANDS_DIR/executive-summary.md"
cp "$SOURCE_DIR/status-trends.md" "$COMMANDS_DIR/status-trends.md"
cp "$SOURCE_DIR/risk-register.md" "$COMMANDS_DIR/risk-register.md"
cp "$SOURCE_DIR/stakeholder-view.md" "$COMMANDS_DIR/stakeholder-view.md"

echo "Installed 8 commands:"
echo ""
echo "  Core Reports:"
echo "  /status-report        Weekly status report with impact metrics and risk detection"
echo "  /executive-summary    VP-ready single-paragraph summary with traffic light status"
echo "  /team-report          Team rollup with bottleneck analysis and manager action items"
echo "  /quarterly-review     Quarter summary with initiative narratives and velocity trends"
echo ""
echo "  Analysis Tools:"
echo "  /okr-update           Map recent work to OKRs with gap analysis and alignment scoring"
echo "  /status-trends        Multi-week trends dashboard with sparkline charts"
echo "  /risk-register        Formal risk register with scoring matrix and mitigations"
echo "  /stakeholder-view     Same data tailored to audience: exec, pm, eng, or external"
echo ""
echo "Quick start:"
echo ""
echo "  /status-report"
echo "  /status-report last 2 weeks"
echo "  /status-report repo:my-org/my-repo"
echo "  /executive-summary org:my-org for:vp"
echo "  /team-report users:alice,bob,carol"
echo "  /quarterly-review Q2 2025"
echo "  /okr-update O1: Ship model router KR1: Reduce latency by 30%"
echo "  /status-trends 8 weeks"
echo "  /risk-register repo:my-org/my-repo"
echo "  /stakeholder-view exec"
echo "  /stakeholder-view pm last 2 weeks"
echo "  /stakeholder-view eng repo:my-org/my-repo"
echo ""
echo "Example outputs:"
echo ""
echo "  /status-report produces:"
echo "    ## Weekly Status Report"
echo "    Period: 2025-06-16 to 2025-06-23"
echo "    Summary: This week shipped streaming support for the inference"
echo "    gateway (PR #42, +312/-45 lines), which unblocks real-time model"
echo "    serving for the enterprise tier. The team also closed 2 deployment"
echo "    issues and completed 6 code reviews. PR #50 (quota management API)"
echo "    has been open 3 days with no reviewer assigned."
echo ""
echo "  /executive-summary produces:"
echo "    ## Executive Summary"
echo "    The AI platform team shipped streaming inference support and"
echo "    closed 5 deployment issues across 4 repos this week, completing"
echo "    3 of 4 Q3 milestone deliverables. Inference latency dropped 40%"
echo "    with the scheduling loop redesign, bringing the enterprise tier"
echo "    within SLA. The quota management API needs a reviewer assigned"
echo "    to stay on track for the July 15 deadline."
echo "    Status: GREEN - 3 of 4 Q3 deliverables complete, 2 weeks of buffer"
echo ""
echo "  /risk-register produces:"
echo "    ## Risk Register"
echo "    Total Risks: 3 (1 High, 2 Medium)"
echo "    R1: Quota API PR unreviewed for 12 days (Score: 16/25 - High)"
echo "    R2: CI flaky on inference-sim integration tests (Score: 9/25 - Med)"
echo "    R3: External API dependency delayed 1 week (Score: 8/25 - Med)"
echo ""
echo "  /stakeholder-view exec produces:"
echo "    ## Executive Status Update"
echo "    Status: GREEN"
echo "    Bottom Line: The platform team completed 3 of 4 Q3 deliverables,"
echo "    reducing AI inference costs by 20% and enabling real-time model"
echo "    serving for enterprise customers."
echo ""
echo "  /stakeholder-view eng produces:"
echo "    ## Engineering Status Update"
echo "    Commits: 14 | PRs Merged: 3 | Avg PR Size: 126 lines"
echo "    Avg PR Cycle Time: 1.8 days"
echo "    Shipped: vLLM scheduling loop optimization (PR #42, +312/-45)"
echo "    Architecture: Moved to event-driven model routing (PR #51)"
echo ""
echo "Optional: Create ~/.status-config to set defaults. See README for format."
echo ""
echo "Done. Commands are ready to use in Claude Code."
